services:

  - type: web
    name: arb-tracker-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: DATABASE_URL
        fromDatabase:
          name: arb-tracker-db
          property: connectionString

      - key: API_URL
        value: "https://arb-tracker-api.onrender.com"

      - key: PYTHON_VERSION
        value: "3.11.9"

  - type: worker
    name: arb-tracker-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run_bot.py"

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: API_URL
        value: "https://arb-tracker-api.onrender.com"

      - key: MINI_APP_URL
        value: "https://arb-tracker-miniapp.pages.dev/"

      - key: DATABASE_URL
        fromDatabase:
          name: arb-tracker-db
          property: connectionString

      - key: PYTHON_VERSION
        value: "3.11.9"

      - key: BOT_MAX_BACKOFF_SEC
        value: "60"

databases:

  - name: arb-tracker-db
    plan: free
    postgresMajorVersion: "16"
